# Propostas por um tempo
GET_ESTILOS_POR_PROJETO = """
SELECT
P.ID AS ID_PROPOSTA,

	CASE 
    	WHEN S.DESCRICAO IS NULL THEN "Cancelada"
        ELSE S.DESCRICAO
    END AS STATUS_PROPOSTA,

C.NAME AS CASA,
A.NOME AS ARTISTA,
DATE_FORMAT(DATA_INICIO, '%d/%m/%y') AS DATA_INICIO, 
DATE_FORMAT(DATA_INICIO, '%H:%i') AS HORARIO_INICIO,
DATE_FORMAT(DATA_FIM, '%d/%m/%y') AS DATA_FIM, 
DATE_FORMAT(DATA_FIM, '%H:%i') AS HORARIO_FIM,
TIMEDIFF(DATA_FIM, DATA_INICIO) AS DURACAO,
DAYNAME(DATA_INICIO) AS DIA_DA_SEMANA,
P.VALOR_BRUTO,
P.VALOR_LIQUIDO,
P.VALOR_BRUTO_OCULTO,
SF.DESCRICAO AS STATUS_FINANCEIRO,
F.FONTE,
P.B2C,
P.ADIANTAMENTO,
C.ID AS ID_CASA,
A.ID AS ID_ARTISTA

FROM T_PROPOSTAS P
LEFT JOIN T_COMPANIES C ON (P.FK_CONTRANTE = C.ID)
LEFT JOIN T_ATRACOES A ON (P.FK_CONTRATADO = A.ID)
LEFT JOIN T_PROPOSTA_STATUS S ON (P.FK_STATUS_PROPOSTA = S.ID)
LEFT JOIN T_PROPOSTA_STATUS_FINANCEIRO SF ON (P.FK_STATUS_FINANCEIRO = SF.ID)
LEFT JOIN T_FONTE F ON (F.ID = P.FK_FONTE)

WHERE P.TESTE = 0 
	AND P.FK_CONTRANTE IS NOT NULL 
    AND P.FK_CONTRATADO IS NOT NULL 
    AND P.DATA_INICIO IS NOT NULL
    AND C.ID = 102
    
   
ORDER BY P.DATA_INICIO ASC;
"""

